// day-07/nanostore-test/src/components/NanoCounter.vue
<template>
  <div class="counter">
    <button @click="subtract()">-</button>
    <pre>{{ count }}</pre>
    <button @click="add()">+</button>
  </div>
</template>

<script>
import { useStore } from '@nanostores/vue';
import { storeCounter } from '../store/counter.js';

export default {
  setup() {
    const $counter = useStore(storeCounter);
    const add = () => storeCounter.set($counter+1)
    const subtract = () => storeCounter.set($counter-1)

    return {
      count:$counter,
      add,
      subtract,
    };
  },
};
</script>

<style>
.counter {
  display: grid;
  font-size: 2em;
  grid-template-columns: repeat(3, minmax(0, 1fr));
  margin-top: 2em;
  place-items: center;
  background-color: greenyellow ;
}
</style>

// day-07/nanostore-test/src/components/NanoCounter.jsx
import { useStore } from '@nanostores/react';
import { storeCounter } from '../store/counter.js';

const counterStyle = {
  display: 'grid',
  fontSize: '2em',
  gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
  placeItems: 'center',
  marginTop:'2em',
  backgroundColor:'blue'
};

export default function Counter() {

  // read the store value with the `useStore` hook
  const $counter = useStore(storeCounter);

  return (
    <>
      <div style={counterStyle}>
        <button onClick={() => storeCounter.set($counter-1)}>-</button>
        <pre>{$counter}</pre>
        <button onClick={() => storeCounter.set($counter+1)}>+</button>
      </div>
    </>
  );
}
